name: "Deployment Tar Artifact Upload"
author: "Pete McWilliams"
description: >-
  Creates a bundled Tar file of the workspace that retains permissions and excludes defined patterns.

branding:
  icon: upload-cloud
  color: orange

inputs:
  name:
    description: >-
      The name of the bundled artifact file.
    required: false
    default: "artifact"
  exclude-file:
    description: >-
      A file describing paths or wildcard patterns to exclude from the artifact bundle.
    required: true
  if-no-files-found:
    description: >-
      The desired behavior if no files are found using the provided path.
      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    required: false
    default: "warn"
  retention-days:
    description: >-
      Duration after which artifact will expire in days. 0 means using default retention.
      Minimum 1 day.
      Maximum 90 days unless changed from the repository settings page.

runs:
  using: "composite"
  steps:
    - shell: "bash"
      run: |
        shopt -s globstar
        mkdir -p ${{ github.workspace }}/artifacts
        tar --anchored --exclude-from=${{ inputs.exclude-file }} -cvf ${{ github.workspace }}/artifacts/artifact_bundle.tar -C ${{ github.workspace }} .

    - uses: "actions/upload-artifact@v3"
      if: success()
      with:
        name: "${{ inputs.name }}"
        path: "${{ github.workspace }}/artifacts/artifact_bundle.tar"
        if-no-files-found: "${{ inputs.if-no-files-found }}"
        retention-days: "${{ inputs.retention-days }}"
